CREATE TABLE IF NOT EXISTS Product (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `product_name` VARCHAR(255) NOT NULL,
    `price` FLOAT UNSIGNED NOT NULL,
    `description` VARCHAR(255) NOT NULL,
    `stock` INT DEFAULT 0,
    `created_on` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_on` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY(id),
    UNIQUE KEY(product_name)
)