CREATE TABLE IF NOT EXISTS Sales (
    `userId` INT UNSIGNED NOT NULL,
    `productId` INT UNSIGNED NOT NULL,
    FOREIGN KEY (`userId`) REFERENCES `User` (`id`)
    ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (`productId`) REFERENCES `Product` (`id`)
    ON DELETE CASCADE ON UPDATE CASCADE
)