CREATE TABLE IF NOT EXISTS Product_Order (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `quantity` INT UNSIGNED NOT NULL,
    `userId` INT UNSIGNED NOT NULL,
    `productId` INT UNSIGNED NOT NULL,
    `created_on` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_on` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY(id),
    FOREIGN KEY(userId) REFERENCES User(id) ON DELETE CASCADE,
    FOREIGN KEY(productId) REFERENCES Product(id) ON DELETE CASCADE
)