CREATE TABLE IF NOT EXISTS Product_Order (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `quantity` INT UNSIGNED NOT NULL,
    `user_id` INT UNSIGNED NOT NULL,
    `product_id` INT UNSIGNED NOT NULL,
    `created_on` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_on` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY(id),
    FOREIGN KEY(user_id) REFERENCES User(id) ON DELETE CASCADE,
    FOREIGN KEY(product_id) REFERENCES Product(id) ON DELETE CASCADE
)